name = "speakeasy"
compatibility_date = "2026-07-16"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "speakeasy-db"
database_id = "local-d1-binding"

[[send_email]]
name = "EMAIL"